2018-10-01 22:45:12 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'TYPE' (CONCEPT: TYPE INTEGER NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CONCEPT"("ID","CHAPTER_ID","DEFINATION","NAME","TYPE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-197]
2018-10-01 22:45:12 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Data conversion error converting "'TYPE' (CONCEPT: TYPE INTEGER NOT NULL)"; SQL statement:
INSERT INTO "PUBLIC"."CONCEPT"("ID","CHAPTER_ID","DEFINATION","NAME","TYPE")VALUES(?,?,?,?,?) -- (?1, ?2, ?3, ?4, ?5) [22018-197]
2018-10-02 11:00:18 jdbc[35]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:136)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:198)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:467)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:706)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:692)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.h2.jdbc.JdbcSQLException: The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 18 more
2018-10-02 12:00:50 jdbc[13]: exception
org.h2.jdbc.JdbcSQLException: Syntax error in SQL statement "SELECT * FROM QUESTION 

SELECT[*] * FROM MCQANSWER"; SQL statement:
SELECT * FROM QUESTION 

SELECT * FROM MCQANSWER [42000-197]
